config/routes.rb
Rails.application.routes.draw do
  
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root 'homes#top'
    resources :users, only: [:index, :edit, :update]
    resources :posts, only: [:show, :destroy]
    resources :tags, only: [:index, :destroy]
  end

  # ユーザー用
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  root 'public/homes#top'
  get "/search", to: "public/searches#search"
  get  '/users/check' => 'public/users#check'
  patch  '/users/withdraw' => 'public/users#withdraw'
  
  scope module: :public do
    resources :users, only: [:show, :edit, :update, :destroy], param: :account_name do
      resource :relationships, only: [:create, :destroy]
        get "followings" => "relationships#followings", as: "followings"
        get "followers" => "relationships#followers", as: "followers"
    end
    resources :posts, only: [:index, :show, :create, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :accounts, only: [:edit, :update, :destroy], param: :account_name
  end
  
  # ゲストログイン用
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   before_action :authenticate_admin!
  
  def top
    @posts = Post.order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="posts-field">
  <% if @posts.present? %>
    <% @posts.each do |post| %>
      <div class="posts-post-field">
        <span class="post-user"><b><%= link_to post.user.name, admin_user_path(post.user.account_name) %></b></span>
        <span class="post-info">@<%= post.user.account_name %></span>
        <span class="post-info">・<%= time_ago_in_words(post.created_at) %>前</span>
        <p class="post-body"><%= link_to post.body, admin_post_path(post.id) %></p>
        <span><i class="fa-solid fa-heart"></i> <%= post.favorites.count %></span>
        <span><%= link_to '<i class="fa-solid fa-comment"></i>'.html_safe, admin_post_path(post.id) %> <%= post.comments.count %></span>
        <span>
          <% if admin_signed_in? %>
            <%= link_to '<i class="fa-solid fa-trash"></i>'.html_safe, admin_post_path(post.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
          <% end %>
        </span>
      </div>
    <% end %>
    <%= paginate @posts %>
  <% else %>
      <p>つぶやきはありません。</p>
  <% end %>
</div>