config/routes.rb
Rails.application.routes.draw do
  
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root 'homes#top'
    resources :users, only: [:index, :edit, :update]
    resources :posts, only: [:show, :destroy]
    resources :tags, only: [:index, :destroy]
  end

  # ユーザー用
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  root 'public/homes#top'
  get "/search", to: "public/searches#search"
  get  '/users/check' => 'public/users#check'
  patch  '/users/withdraw' => 'public/users#withdraw'
  
  scope module: :public do
    resources :users, only: [:show, :edit, :update, :destroy], param: :account_name do
      resource :relationships, only: [:create, :destroy]
        get "followings" => "relationships#followings", as: "followings"
        get "followers" => "relationships#followers", as: "followers"
    end
    resources :posts, only: [:index, :show, :create, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :accounts, only: [:edit, :update, :destroy], param: :account_name
  end
  
  # ゲストログイン用
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= t("errors.template.header", model: obj.model_name.human, count: obj.errors.count) %></h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
	<p>© 2024 .ZIP INC. ALL RIGHT RESERVED</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <% if user_signed_in? || admin_signed_in? %>
    <%= image_tag 'site-logo.png', class: "header-logo" %>
    <nav class="header-nav">
      <ul class="nav-list">
        <% if admin_signed_in? %>
          <li>
            <%= link_to admin_root_path do %>
              <p class="nav-item"><i class="fa-solid fa-comments"></i> つぶやき</p>
            <% end %>
          </li>
          <li>
            <%= link_to admin_users_path do %>
              <p class="nav-item"><i class="fa-solid fa-user-group"></i> ユーザー</p>
            <% end %>
          </li>
          <li>
            <%= link_to admin_tags_path do %>
              <p class="nav-item"><i class="fa-solid fa-tag"></i> タグ</p>
            <% end %>
          </li>
          <li>
            <p class="nav-item">
              <%= link_to  destroy_admin_session_path, method: :delete do %>
                <i class="fa-solid fa-right-from-bracket"></i> ログアウト
              <% end %>
            </p>
          </li>
        <% elsif user_signed_in? %>
          <li>
              <%= link_to user_path(current_user.account_name) do %>
                <p class="nav-item first-item"><i class="fa-solid fa-house"></i> マイルーム</p>
              <% end %>
            </li>
          <li>
            <%= link_to posts_path do %>
              <p class="nav-item"><i class="fa-solid fa-comments"></i> つぶやき</p>
            <% end %>
          </li>
          <li>
            <%= link_to user_followings_path(current_user.account_name) do %>
              <p class="nav-item"><i class="fa-solid fa-user-group"></i> フレンド</p>
            <% end %>
          </li>
          <li>
            <p class="nav-item">
              <%= link_to  destroy_user_session_path, method: :delete do %>
                <i class="fa-solid fa-right-from-bracket"></i> ログアウト
              <% end %>
            </p>
          </li>
        <% end %>
      </ul>
    </nav>
    <% if user_signed_in? %>
    <div class="sp-menu">
      <input type="checkbox" id="sp-menu__check">
      <label for="sp-menu__check" class="sp-menu__box">
        <span></span>
      </label>
      <div class="sp-menu__content">
        <ul class="sp-menu__list">
          <li class="sp-menu__item">
              <%= link_to user_path(current_user.account_name) do %>
                <i class="fa-solid fa-house"></i> マイルーム
              <% end %>
            </a>
          </li>
          <li class="sp-menu__item">
              <%= link_to posts_path do %>
                <i class="fa-solid fa-comments"></i> つぶやき
              <% end %>
            </a>
          </li>
          <li class="sp-menu__item">
              <%= link_to user_followings_path(current_user.account_name) do %>
                <i class="fa-solid fa-user-group"></i> フレンド
              <% end %>
            </a>
          </li>
          <li class="sp-menu__item">
              <%= link_to  destroy_user_session_path, method: :delete do %>
                <i class="fa-solid fa-right-from-bracket"></i> ログアウト
              <% end %>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <% end %>
  <% else %>
    <%= image_tag 'site-logo.png', class: "header-logo-2" %>
  <% end %>
 </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>.zip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <script src="https://kit.fontawesome.com/c5d2215689.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/no_sidebar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>.zip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/c5d2215689.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="body-top">
    <main>
      <%= yield %>
    </main>
  </body>
</html>